# -*- coding: utf-8 -*-
"""LGMVIP-DataScience-4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18YnQjyyjR2YWX_MDX6JyM6zIRjcODJlg

Since .ipynb file is not viewable in GitHub, uploading as .py file. For outputs, please change the format. Thank you

- Preethi Ponnusamy
"""

import cv2
from google.colab.patches import cv2_imshow

image = cv2.imread("LGMVIP_DataScience_2.jpg")
cv2_imshow(image)

#grayscale

gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2_imshow(gray_image)

#invert the image

inverted_image = 255 - gray_image
cv2_imshow(inverted_image)

# Gaussian Blur

blur = cv2.GaussianBlur(inverted_image, (21,21), 0)

blur

#inverting the blurred image

inverted_blurred = 255 - blur
pencil_sketch = cv2.divide(gray_image, inverted_blurred, scale = 256.0)

cv2_imshow(pencil_sketch)

